model_path: assets/panda_tray/world.xml
control:
  substeps: 10
  Kp: [1200.0, 1000.0, 1000.0, 800.0, 300.0, 200.0, 50.0]
  Ki: [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
  Kd: [50.0, 50.0, 50.0, 20.0, 20.0, 20.0, 10.0]
  tau_limits: [87, 87, 87, 87, 12, 12, 12]
  delta_tau_max: 1.0
  max_speed: 0.3
  stabilization_steps: 100

debug:
  debug_prints: false
  debug_interval_steps: 100

limits:
  joint_high: [2.8973, 1.7628, 2.8973, -0.0698, 2.8973, 3.7525, 2.8973]
  joint_low: [-2.8973, -1.7628, -2.8973, -3.0718, -2.8973, -0.0175, -2.8973]

start:
  cylinder: [0.189, 0.186, 0.9]
  joints: [0.1, -1.24, 0.29, -2.3, 0.12, 2.68, -0.63]
  tray_pos: [0.189, 0.186, 0.848]
  tray_rpy: [0.0, 0.0, -2.883]

goal:
  max_steps: 50000
  pos_tolerance: 0.03
  success_hold_steps: 100
  tray_pos: [0.151, 0.614, 0.958]
  tray_rpy: [0.0, 0.0, -1.918]
  yaw_tolerance_deg: 10.0
  relaxed_yaw_tolerance_deg: 360.0

observation: 
  cylinder_noise_std_pos: 0.0
  cylinder_noise_std_vel: 0.0
  noise_std_pos: 0.0
  noise_std_vel: 0.0
  use_jacobian_tray_obs: false

penalties: 
  base_step: -0.1
  drop: -1000.0
  idle_action: -0.1
  slant_penalty_max: -0.5
  slant_penalty_min: -0.1
  slide_penalty_max: -0.2
  slide_penalty_min: -0.05
  topple: -500.0

progress: 
  min_delta: 6e-5
  max_delta: 1e-4
  progress_max: 1.5
  progress_min: 0.05

slant_angle:
  slant_angle_max: 20
  slant_angle_min: 2

rim_zone: 
  slide_threshold: 0.01
  x_half: 0.05
  y_half: 0.09

drop_check: {center_to_center_margin: 0.09}

success_reward: 
  min_bonus: 100
  max_bonus: 1000.0
  stay_reward: 50.0

curriculum:
  num_phases: 5
  current_phase: 1
  phase_method: "linear"
  phase_exp_rate: 3.0
  max_success_threshold: 10