name: franka_tray_rl
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pip
  - numpy
  - scipy
  - matplotlib
  - jupyter
  - ipykernel
  - mujoco>=3.1        # official MuJoCo Python bindings
  - gymnasium>=0.28
  - shimmy>=1.3.0      # gym<->gymnasium compatibility layer (SB3 uses it)
  - stable-baselines3  # v2.x from conda-forge is Gymnasium-ready
  - pytorch            # CPU-only; for GPU use "pytorch-cuda" (see notes)
  - tensorboard
  - yaml               # libyaml bindings (PyYAML comes via pip below)
  - pip:
      - mujoco-python-viewer
      - transforms3d
      - hydra-core
      - omegaconf
      - pyyaml