_wandb:
    value:
        cli_version: 0.22.3
        code_path: code/scripts/traypose/train_traypose.py
        e:
            78gima01le286yqpy88hh02l7z7dj844:
                codePath: scripts/traypose/train_traypose.py
                codePathLocal: scripts/traypose/train_traypose.py
                email: thinkminator1024@gmail.com
                executable: /home/think/anaconda3/envs/franka_tray_rl/bin/python
                git:
                    commit: 6464a0785eff35d10763270a516da0db0aee2cae
                    remote: git@github.com:Thinkminator/franka_tray_rl.git
                host: think-Legion-Pro-7-16IRX8H
                os: Linux-6.8.0-86-generic-x86_64-with-glibc2.35
                program: /home/think/ME5418/franka_tray_rl/scripts/traypose/train_traypose.py
                python: CPython 3.9.23
                root: /home/think/ME5418/franka_tray_rl
                startedAt: "2025-11-05T14:26:39.253783Z"
                writerId: 78gima01le286yqpy88hh02l7z7dj844
        m: []
        python_version: 3.9.23
        t:
            "1":
                - 1
            "2":
                - 1
            "3":
                - 13
                - 16
                - 35
            "4": 3.9.23
            "5": 0.22.3
            "12": 0.22.3
            "13": linux-x86_64
batch_size:
    value: 256
gamma:
    value: 0.99
learning_rate:
    value: 0.0001
n_envs:
    value: 8
n_steps:
    value: 1024
total_timesteps:
    value: 1000000
